name: Deploy Frontend to Vercel

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  # ==========================================
  # Job 1: 린트 & 타입 체크
  # ==========================================
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v3

      - name: 📦 Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: 📚 Install dependencies
        run: npm ci

      - name: 🔍 Run ESLint
        run: npm run lint --if-present

      - name: ✔️ TypeScript type check
        run: npm run type-check --if-present || npx tsc --noEmit

      - name: 🧪 Run tests
        run: npm run test --if-present || echo "No test script found"

  # ==========================================
  # Job 2: Vercel 배포 (Preview)
  # ==========================================
  deploy-preview:
    needs: lint-and-test
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v3

      - name: 🚀 Deploy to Vercel (Preview)
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          scope: ${{ secrets.VERCEL_ORG_ID }}

      - name: 📝 Comment PR with deployment URL
        uses: actions/github-script@v6
        if: github.event_name == 'pull_request'
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '✅ Preview deployment completed!\n\n🌐 Visit your preview: https://${{ env.VERCEL_URL }}'
            })

  # ==========================================
  # Job 3: Vercel 배포 (Production)
  # ==========================================
  deploy-production:
    needs: lint-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v3

      - name: 🚀 Deploy to Vercel (Production)
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: "--prod"
          scope: ${{ secrets.VERCEL_ORG_ID }}

      - name: ✅ Production deployment successful
        run: |
          echo "========================================"
          echo "🎉 PRODUCTION DEPLOYMENT SUCCESSFUL!"
          echo "========================================"
          echo "🌐 Production URL: https://${{ env.VERCEL_URL }}"
          echo "========================================"

  # ==========================================
  # Job 4: 헬스 체크 & 알림
  # ==========================================
  # health-check:
  #   needs: deploy-production
  #   runs-on: ubuntu-latest
  #   if: github.ref == 'refs/heads/main' && github.event_name == 'push'

  #   steps:
  #     - name: 🏥 Health check
  #       run: |
  #         echo "========================================"
  #         echo "🏥 Performing health check"
  #         echo "========================================"

  #         MAX_ATTEMPTS=10
  #         ATTEMPT=0

  #         while [ $ATTEMPT -lt $MAX_ATTEMPTS ]; do
  #           ATTEMPT=$((ATTEMPT+1))
  #           echo "⏳ Health check attempt $ATTEMPT/$MAX_ATTEMPTS..."

  #           if curl -f https://${{ env.VERCEL_URL }} 2>/dev/null; then
  #             echo ""
  #             echo "========================================"
  #             echo "✅ APPLICATION HEALTHY!"
  #             echo "========================================"
  #             echo "🌐 URL: https://${{ env.VERCEL_URL }}"
  #             echo "========================================"
  #             exit 0
  #           fi

  #           echo "⏳ Waiting 5s before next attempt..."
  #           sleep 5
  #         done

  #         echo ""
  #         echo "========================================"
  #         echo "⚠️ Health check inconclusive (timeout)"
  #         echo "========================================"
  #         exit 0

  #     - name: 📧 Notify Slack (Optional)
  #       uses: slackapi/slack-github-action@v1.24.0
  #       if: always()
  #       with:
  #         payload: |
  #           {
  #             "text": "Frontend Deployment Status",
  #             "blocks": [
  #               {
  #                 "type": "section",
  #                 "text": {
  #                   "type": "mrkdwn",
  #                   "text": "*Vercel Deployment*\n✅ Production deployment completed!\n🌐 URL: https://${{ env.VERCEL_URL }}"
  #                 }
  #               }
  #             ]
  #           }
  #       env:
  #         SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  #         SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
